# Site settings
title: WUXX BLOG
header-img: img/home-bg.jpg
email: 935817127@qq.com
description: "This is Wuxx's Blog"
baseurl: "/myblog"
url: "http://wxzwsj197950.hithub.io/myblog"
twitter_username: SBootstrap
github_username:  davidtmiller
facebook_username:  IronSummitMedia

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
