# Site settings
title: 吴XX的博客
header-img: img/home-bg.jpg
email: 935817127@qq.com
description: "这是吴XX的博客"
baseurl: "/myblog"
url: "http://wxzwsj197950.github.io/myblog/"
twitter_username: SBootstrap
github_username:  wxzwsj197950
facebook_username:  IronSummitMedia
qq_username: 935817127
# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
